name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./root
        steps:
            - name: Checkout
              uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false
            - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: |
                  npm install
                  npm run build
                  npm run deploy
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  github_token: ${{ secrets.TOKEN }}
                  branch: gh-pages
                  folder: root/out
                  clean: true
